version: '3.4'

# TO TEST RUN: docker-compose -f docker-compose.yml -f docker-compose.multi.yml up --build

services:
  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - voting-api-01
      - voting-api-02
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yml"

  grafana:
    image: grafana/grafana:latest
    depends_on: 
      - prometheus
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki:/etc/loki
      - ./loki_data:/loki
    user: "root"
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3100/ready 
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  promtail:
    image: grafana/promtail:2.8.0
    depends_on:
      - loki
    command:
      - -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log

  voting-api-01:
    image: ${DOCKER_REGISTRY-}votinggrafana
    build:
      context: .
      dockerfile: Voting.Grafana/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - OTEL_RESOURCE_ATTRIBUTES=service.name=voting-grafana-api-01,service.namespace=Voting.Grafana,service.version=1.0,host.name=`HOSTNAME`
    ports:
      - "8080:8080"
    depends_on:
      loki:
        condition: service_healthy
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
 
  voting-api-02:
    image: ${DOCKER_REGISTRY-}votinggrafana
    build:
      context: .
      dockerfile: Voting.Grafana/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8081
      - OTEL_RESOURCE_ATTRIBUTES=service.name=voting-grafana-api-02,service.namespace=Voting.Grafana,service.version=1.0,host.name=`HOSTNAME`
    ports:
      - "8081:8081"
    depends_on:
      loki:
        condition: service_healthy
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  k6:
    image: loadimpact/k6:latest
    volumes:
      - ./k6/tests:/scripts
    entrypoint: tail -f /dev/null
    links:
      - voting-api-01
      - voting-api-02
    depends_on:
      - voting-api-01
      - voting-api-02